# Generated by Django 4.1.7 on 2023-04-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=32, verbose_name='Task ID')),
                ('ormq_id', models.IntegerField(blank=True, null=True, verbose_name='Queue record ID')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='Task cancellation requested')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.AddConstraint(
            model_name='taskhandle',
            constraint=models.UniqueConstraint(fields=('task_id',), name='uniq_task_handle_task_id'),
        ),
    ]
