# Generated by Django 4.1.8 on 2023-04-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_logentry_alter_semaphorerecord_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Log entries'},
        ),
    ]
