# Generated by Django 4.2 on 2023-04-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_alter_logentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhandle',
            name='max_tries',
            field=models.IntegerField(default=1, help_text='max number of tries'),
        ),
        migrations.AddField(
            model_name='taskhandle',
            name='next',
            field=models.ForeignKey(blank=True, help_text='handle ID of the next task try', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_handle', to='helpers.taskhandle'),
        ),
        migrations.AddField(
            model_name='taskhandle',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='handle ID of the previous task try', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_handle', to='helpers.taskhandle'),
        ),
        migrations.AddField(
            model_name='taskhandle',
            name='try_num',
            field=models.IntegerField(default=1, help_text='try number'),
        ),
    ]
