# Generated by Django 4.2 on 2023-04-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_taskhandle_max_tries_taskhandle_next_taskhandle_prev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhandle',
            name='max_tries',
            field=models.IntegerField(default=1, editable=False, help_text='max number of tries'),
        ),
        migrations.AlterField(
            model_name='taskhandle',
            name='next',
            field=models.ForeignKey(blank=True, editable=False, help_text='handle of the next task try', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_handle', to='helpers.taskhandle'),
        ),
        migrations.AlterField(
            model_name='taskhandle',
            name='prev',
            field=models.ForeignKey(blank=True, editable=False, help_text='handle of the previous task try', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_handle', to='helpers.taskhandle'),
        ),
        migrations.AlterField(
            model_name='taskhandle',
            name='try_num',
            field=models.IntegerField(default=1, editable=False, help_text='try number'),
        ),
    ]
